language: node_js
before_install:
  - npm install -g npm@2
  - npm install -g npm
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
branches:
  only:
  - master
notifications:
email:
    - newmansam@outlook.com
script: npm test
